services:
  statewm-server:
    build: stat-service/stat-server
    ports:
      - "9090:9090"
    depends_on:
      - statewm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://statewm-db:5432/explore-with-me
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345

  statewm-db:
    image: postgres:16.1
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  mainewm-server:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mainewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - STAT_SERVER_URL=http://statewm-server:9090
    depends_on:
      - statewm-db
      - mainewm-db

  mainewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
